spring.application.name=BookPass


spring.datasource.url=jdbc:postgresql://localhost:5432/bookpass_db
spring.datasource.username=postgres
spring.datasource.password=holberton

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.docker.compose.enabled=false